import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon'
import 'vue-awesome/icons/brands/linkedin'
import 'vue-awesome/icons/brands/facebook'
import 'vue-awesome/icons/brands/instagram'
import 'vue-awesome/icons/brands/twitter'
import 'vue-awesome/icons/phone-alt'
import 'vue-awesome/icons/envelope'
import 'vue-awesome/icons/arrow-right'
import 'vue-awesome/icons/arrow-left'
import 'vue-awesome/icons/star'
import 'vue-awesome/icons/check-double'
import 'vue-awesome/icons/grip-horizontal'
import 'vue-awesome/icons/map-marker-alt'
import 'vue-awesome/icons/regular/clock'
import 'vue-awesome/icons/regular/calendar'
import 'vue-awesome/icons/regular/file-alt'
// require('vue-awesome/icons')

Vue.component('icon', Icon)
